# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get install awscli

- script: |
    npm install
    npm test
  displayName: 'npm install and test'

- script: |
    aws s3 cp cloudformation-stack.json s3://azdo-staging-s3-bucket -a $(AWS_ACCESS_KEY_ID) -s $(AWS_SECRET_KEY_ID)
    zip -r -X build.zip .
    aws s3 cp build.zip s3://azdo-staging-s3-bucket -a $(AWS_ACCESS_KEY_ID) -s $(AWS_SECRET_KEY_ID)
  displayName: 'upload CloudFormation template and Lambda function ZIP build to staging bucket'
